spring.application.name=Expense

#MYSQL CONFIGURATION
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3307/fin
spring.datasource.username=root
spring.datasource.password=789521

#JPA HIBERNATE CONFIGURATION

spring.jpa.hibernate.ddl-auto=update

spring.jpa.open-in-view=false

#PORT NUMER
server.port=2544

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nerellajathin2006@gmail.com
spring.mail.password=topk iill oaoj qxdc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true